rpc:
  listen: tcp://127.0.0.1:6001

http:
  address: 0.0.0.0:9000
  middleware: [ "gzip" ]

gzip:
  level: 5

server:
  command: "php server.php"
  relay: "pipes"

grpc:
  listen: "tcp://0.0.0.0:9001"
  proto: "./proto"
